### ISSUE TITLE
Replace security group list instead of appending?

### ISSUE THREAD

**Issue by stevenringo** [airplanedev/terraform-aws-airplane-cluster#11]
Hi,

I am specifying my own security group, yet the module also creates its own and links it. Shouldn't this override any defaults created by the module?

Thanks

**Comment by joshma** [comment]
It's something we've considered - we wanted to ensure that the agent had egress access to Airplane APIs, which is why we don't replace it currently. I suppose we could ask users to ensure the right egress is enabled on any security groups they specify.

Out of curiosity, do you have any hard requirements for SGs, or is it more security hygiene?

**Comment by joshma** [comment]
@stevenringo Got it, makes sense. We'll have to figure out how to make this backwards compatible, but we'll look into a fix here.

**Comment by joshma** [comment]
@stevenringo we've released v0.4.11 with support for `create_egress_security_group=false` to disable, give it a spin!
